apiVersion: v1
kind: Pod
metadata:
  name: mlops-k8s-pod
spec:
  containers:
  - name: hw02cont
    image: aitkachenko/hw02:v1
    ports:
    - containerPort: 18000
    resources:
      requests:
        memory: "256Mi"
        cpu: "125m"
      limits:
        memory: "512Mi"
        cpu: "750m"
