apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: mlops-k8s-pod
  labels:
    app: online-inference
spec:
  replicas: 3
  selector:
    matchLabels: 
      app: online-inference
  template:
    metadata:
      name: online-inference-replicaset
      labels:
        app: online-inference
    spec:
      containers:
        - name: hw02contv3
          image: aitkachenko/hw02:v3
          ports:
            - containerPort: 18000
          resources:
            requests:
              memory: "256Mi"
              cpu: "125m"
            limits:
              memory: "512Mi"
              cpu: "750m"
