_target_ : src.data.dataloader.DataLoader
target: condition
categorical_features:
  - name: sex
    values: [0,1]
  - name: cp
    values: [0, 1, 2, 3]
  - name: fbs
    values: [0, 1]
  - name: restecg
    values: [0, 1, 2]
  - name: exang
    values: [0, 1]
  - name: slope
    values: [0, 1, 2]
  - name: ca
    values: [0, 1, 2, 3]
  - name: thal
    values: [0, 1, 2]

