_target_ : src.model.trainer.Trainer
data: ./data/raw/heart_cleveland_upload.csv
model:
    - scaler:
        _target_: sklearn.preprocessing.StandardScaler
    - model:
        _target_: sklearn.neighbors.KNeighborsClassifier
save_to: ./models/knn.pkl
