_target_ : src.model.trainer.Trainer
data: ./data/raw/heart_cleveland_upload.csv
model:
    - scaler:
        _target_: sklearn.preprocessing.StandardScaler
    - model:
        _target_: sklearn.linear_model.LogisticRegression
save_to: ./models/log_reg.pkl
